const api = window.electronAPI;

export const ipc = {
  getConfig: () => api.getConfig(),
  openInIDE: (path: string, ide: string) => api.openInIDE(path, ide),
  openInFinder: (path: string) => api.openInFinder(path),
  getDbPath: () => api.getDbPath(),
  revealDb: () => api.revealDb(),
  setTheme: (mode: import("./types").ThemeMode) => api.setTheme(mode),
  runSync: (cmd: string) => api.runSync(cmd),
  selectDirectory: () => api.selectDirectory(),
  scanRepos: (wsPath: string) => api.scanRepos(wsPath),
  initRepo: (projectPath: string) => api.initRepo(projectPath),
  cloneRepo: (repoUrl: string, targetPath: string) => api.cloneRepo(repoUrl, targetPath),
  isGitRepo: (dirPath: string) => api.isGitRepo(dirPath),
  gitBranch: (dirPath: string) => api.gitBranch(dirPath),
  deleteDirectory: (dirPath: string) => api.deleteDirectory(dirPath),
  runStreaming: (id: string, cmd: string) => api.runStreaming(id, cmd),
  cancelCommand: (id: string) => api.cancelCommand(id),
  onStdout: (cb: (id: string, chunk: string) => void) => api.onStdout(cb),
  onStderr: (cb: (id: string, chunk: string) => void) => api.onStderr(cb),
  onComplete: (cb: (id: string, exitCode: number) => void) => api.onComplete(cb),
  removeShellListeners: () => api.removeShellListeners(),
  getWorkspaces: () => api.getWorkspaces(),
  createWorkspace: (data: { name: string; org: string; path: string }) => api.createWorkspace(data),
  deleteWorkspace: (id: string) => api.deleteWorkspace(id),
  getActiveWorkspace: () => api.getActiveWorkspace(),
  setActiveWorkspace: (id: string) => api.setActiveWorkspace(id),
  getProjects: (workspaceId: string) => api.getProjects(workspaceId),
  createProject: (data: Parameters<typeof api.createProject>[0]) => api.createProject(data),
  updateProject: (id: string, data: Parameters<typeof api.updateProject>[1]) => api.updateProject(id, data),
  deleteProject: (id: string) => api.deleteProject(id),
  getProject: (id: string) => api.getProject(id),
  setSetupComplete: (val: boolean) => api.setSetupComplete(val),
  exportConfig: () => api.exportConfig(),
  importConfig: (json: string) => api.importConfig(json),
  getTools: (projectId: string) => api.getTools(projectId),
  createTool: (data: Parameters<typeof api.createTool>[0]) => api.createTool(data),
  deleteTool: (id: string) => api.deleteTool(id),
  updateTool: (id: string, data: Parameters<typeof api.updateTool>[1]) => api.updateTool(id, data),
  discoverScripts: (projectPath: string) => api.discoverScripts(projectPath),
  startProcess: (data: Parameters<typeof api.startProcess>[0]) => api.startProcess(data),
  stopProcess: (id: string) => api.stopProcess(id),
  listProcesses: () => api.listProcesses(),
  clearProcess: (id: string) => api.clearProcess(id),
  clearAllStopped: () => api.clearAllStopped(),
  getProcessLogs: (id: string) => api.getProcessLogs(id),
  getRunningCount: () => api.getRunningCount(),
  getProcessEnv: (id: string) => api.getProcessEnv(id),
  onProcessUpdate: (cb: (entry: import("./types").ProcessEntry) => void) => api.onProcessUpdate(cb),
  onProcessOutput: (cb: (id: string, chunk: string) => void) => api.onProcessOutput(cb),
} as const;
