const api = window.electronAPI;

export const ipc = {
  getConfig: () => api.getConfig(),
  openInIDE: (path: string, ide: string) => api.openInIDE(path, ide),
  openInFinder: (path: string) => api.openInFinder(path),
  getDbPath: () => api.getDbPath(),
  revealDb: () => api.revealDb(),
  setAICli: (cli: import("./types").AICli) => api.setAICli(cli),
  getAIStatus: (cli: import("./types").AICli) => api.getAIStatus(cli),
  setTheme: (mode: import("./types").ThemeMode) => api.setTheme(mode),
  runSync: (cmd: string) => api.runSync(cmd),
  selectDirectory: () => api.selectDirectory(),
  scanRepos: (wsPath: string) => api.scanRepos(wsPath),
  initRepo: (projectPath: string) => api.initRepo(projectPath),
  cloneRepo: (repoUrl: string, targetPath: string) => api.cloneRepo(repoUrl, targetPath),
  isGitRepo: (dirPath: string) => api.isGitRepo(dirPath),
  gitBranch: (dirPath: string) => api.gitBranch(dirPath),
  deleteDirectory: (dirPath: string) => api.deleteDirectory(dirPath),
  runStreaming: (id: string, cmd: string) => api.runStreaming(id, cmd),
  cancelCommand: (id: string) => api.cancelCommand(id),
  onStdout: (cb: (id: string, chunk: string) => void) => api.onStdout(cb),
  onStderr: (cb: (id: string, chunk: string) => void) => api.onStderr(cb),
  onComplete: (cb: (id: string, exitCode: number) => void) => api.onComplete(cb),
  removeShellListeners: () => api.removeShellListeners(),
  getWorkspaces: () => api.getWorkspaces(),
  createWorkspace: (data: { name: string; org: string; path: string }) => api.createWorkspace(data),
  deleteWorkspace: (id: string) => api.deleteWorkspace(id),
  getActiveWorkspace: () => api.getActiveWorkspace(),
  setActiveWorkspace: (id: string) => api.setActiveWorkspace(id),
  getProjects: (workspaceId: string) => api.getProjects(workspaceId),
  createProject: (data: Parameters<typeof api.createProject>[0]) => api.createProject(data),
  updateProject: (id: string, data: Parameters<typeof api.updateProject>[1]) => api.updateProject(id, data),
  deleteProject: (id: string) => api.deleteProject(id),
  getProject: (id: string) => api.getProject(id),
  setSetupComplete: (val: boolean) => api.setSetupComplete(val),
  exportConfig: () => api.exportConfig(),
  importConfig: (json: string) => api.importConfig(json),
  getTools: (projectId: string) => api.getTools(projectId),
  createTool: (data: Parameters<typeof api.createTool>[0]) => api.createTool(data),
  deleteTool: (id: string) => api.deleteTool(id),
  updateTool: (id: string, data: Parameters<typeof api.updateTool>[1]) => api.updateTool(id, data),
  discoverScripts: (projectPath: string) => api.discoverScripts(projectPath),
  startProcess: (data: Parameters<typeof api.startProcess>[0]) => api.startProcess(data),
  stopProcess: (id: string) => api.stopProcess(id),
  listProcesses: () => api.listProcesses(),
  clearProcess: (id: string) => api.clearProcess(id),
  clearAllStopped: () => api.clearAllStopped(),
  getProcessLogs: (id: string) => api.getProcessLogs(id),
  getRunningCount: () => api.getRunningCount(),
  getProcessEnv: (id: string) => api.getProcessEnv(id),
  onProcessUpdate: (cb: (entry: import("./types").ProcessEntry) => void) => api.onProcessUpdate(cb),
  onProcessOutput: (cb: (id: string, chunk: string) => void) => api.onProcessOutput(cb),
  scanMachine: () => api.scanMachine(),
  fixShellConfig: (file: string, line: string) => api.fixShellConfig(file, line),
  checkBrewOutdated: () => api.checkBrewOutdated(),
  setPyenvGlobal: (version: string) => api.setPyenvGlobal(version),
  checkMachineUpdates: () => api.checkMachineUpdates(),
  githubFetch: () => api.githubFetch(),
  githubCache: () => api.githubCache(),
  githubCheck: () => api.githubCheck(),
  githubUserOrgs: () => api.githubUserOrgs(),
  updateWorkspace: (id: string, data: Parameters<typeof api.updateWorkspace>[1]) => api.updateWorkspace(id, data),
  onGithubUpdate: (cb: (data: import("./types").GitHubData) => void) => api.onGithubUpdate(cb),
  getAgentContext: (data: Parameters<typeof api.getAgentContext>[0]) => api.getAgentContext(data),
  getCodexRepoSetup: (data: Parameters<typeof api.getCodexRepoSetup>[0]) => api.getCodexRepoSetup(data),
  getSkillStudioTargets: (data: Parameters<typeof api.getSkillStudioTargets>[0]) => api.getSkillStudioTargets(data),
  readSkillPackage: (filePath: string, data: Parameters<typeof api.readSkillPackage>[1]) => api.readSkillPackage(filePath, data),
  saveSkillPackage: (data: Parameters<typeof api.saveSkillPackage>[0]) => api.saveSkillPackage(data),
  readAgentContextFile: (filePath: string) => api.readAgentContextFile(filePath),
  saveAgentContextFile: (filePath: string, content: string) => api.saveAgentContextFile(filePath, content),
  createAgentContextDirectory: (dirPath: string) => api.createAgentContextDirectory(dirPath),
  deleteAgentContextSkill: (filePath: string) => api.deleteAgentContextSkill(filePath),
  setAgentContextPluginEnabled: (pluginId: string, enabled: boolean) => api.setAgentContextPluginEnabled(pluginId, enabled),
  // PR Detail
  fetchPRDetail: (owner: string, repo: string, number: number) => api.fetchPRDetail(owner, repo, number),
  fetchPRHeadSha: (owner: string, repo: string, number: number) => api.fetchPRHeadSha(owner, repo, number),
  fetchFilePatch: (owner: string, repo: string, number: number, filePath: string) => api.fetchFilePatch(owner, repo, number, filePath),
  postPRComment: (owner: string, repo: string, number: number, body: string) => api.postPRComment(owner, repo, number, body),
  replyToThread: (owner: string, repo: string, number: number, commentId: string, body: string) => api.replyToThread(owner, repo, number, commentId, body),
  submitReview: (owner: string, repo: string, number: number, event: string, body?: string) => api.submitReview(owner, repo, number, event, body),
  resolveThread: (owner: string, repo: string, number: number, threadId: string) => api.resolveThread(owner, repo, number, threadId),
  closePR: (owner: string, repo: string, number: number) => api.closePR(owner, repo, number),
  // Agents
  startAgent: (data: Parameters<typeof api.startAgent>[0]) => api.startAgent(data),
  cancelAgent: (id: string) => api.cancelAgent(id),
  listAgents: () => api.listAgents(),
  getAgentLogs: (id: string) => api.getAgentLogs(id),
  clearAgent: (id: string) => api.clearAgent(id),
  clearAllCompletedAgents: () => api.clearAllCompletedAgents(),
  getAgentRunningCount: () => api.getAgentRunningCount(),
  runAgentPrompt: (cli: string, prompt: string) => api.runAgentPrompt(cli, prompt),
  onAgentUpdate: (cb: (task: import("./pr-types").AgentTask) => void) => api.onAgentUpdate(cb),
  onAgentOutput: (cb: (id: string, chunk: string) => void) => api.onAgentOutput(cb),
  // Rubric
  getRubricCategories: () => api.getRubricCategories(),
  saveRubricCategories: (categories: import("./pr-types").RubricCategory[]) => api.saveRubricCategories(categories),
  getRubricThresholds: () => api.getRubricThresholds(),
  saveRubricThresholds: (thresholds: import("./pr-types").RubricThresholds) => api.saveRubricThresholds(thresholds),
  // PR Cache
  getPrCache: (prId: string) => api.getPrCache(prId),
  listPrCaches: () => api.listPrCaches(),
  upsertPrCache: (prId: string, fields: Partial<import("./pr-types").PRCacheEntry>) => api.upsertPrCache(prId, fields),
  cleanupPrCache: () => api.cleanupPrCache(),
  // PR Discussions
  getDiscussions: (prId: string) => api.getDiscussions(prId),
  createDiscussion: (data: Parameters<typeof api.createDiscussion>[0]) => api.createDiscussion(data),
  addDiscussionMessage: (data: Parameters<typeof api.addDiscussionMessage>[0]) => api.addDiscussionMessage(data),
  deleteDiscussion: (id: string) => api.deleteDiscussion(id),
  // Worktrees
  listWorktrees: (repoPath: string) => api.listWorktrees(repoPath),
  checkWorktreeSyncStatus: (repoPath: string, worktreePath: string) => api.checkWorktreeSyncStatus(repoPath, worktreePath),
  createWorktreeForBranch: (repoPath: string, branch: string, targetPath?: string) => api.createWorktreeForBranch(repoPath, branch, targetPath),
  removeWorktree: (repoPath: string, worktreePath: string) => api.removeWorktree(repoPath, worktreePath),
  pruneWorktrees: (repoPath: string) => api.pruneWorktrees(repoPath),
} as const;
